### ISSUE TITLE
Polylang Pro 3.3 (with ACF Pro) overwrites & orphans language-based field meta values

### ISSUE THREAD

**Issue by E-VANCE** [polylang/polylang#1164]
## Prerequisites

- [x] This is not a usage question
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang Pro `v3.3`
2. Install latest version of ACF Pro
3. Create a repeater field which holds a couple of nested fields
4. Enter some date and create a translation of the post (CPT – content duplication _activated_, synching for custom fields _deactivated_)
5. Now edit something in one language version of the post
6. The other post loses its repeater data (fields blank) due to a mismatch of field meta values

I'll gladly spin up a seperate staging env with all of our data and config so you can test 'live' there.

Downgrading to `v3.2.8` fixes the issue.

## Further information

Comparing the two versions (`v3.2.8` vs. `v3.3`) I found that there has been a rewrite regarding the ACF meta sync functionality and it _could_ be that the missing conditional within `copy_private_metas()` renders the faulty behaviour...?

![CleanShot 2022-12-13 at 16 10 32](https://user-images.githubusercontent.com/4123541/207388446-637f32f4-7868-474d-b3a5-cdf01d5341d8.png)

## Screenshots

Find attached screenshots of our DB showing

1. A German post (DE) being rewritten to point towards `field_produktionen_en_xxx` (changing those to read `field_produktionen_de_xxx` again fixes the issue but they are being overwritten again...)
2. Only select fields being rewritten on an English (EN) post

![CleanShot 2022-12-13 at 16 37 04](https://user-images.githubusercontent.com/4123541/207388010-75643f0b-0d2d-4bb3-bdb5-c5bf60c1f0e3.png)
![CleanShot 2022-12-13 at 16 37 56](https://user-images.githubusercontent.com/4123541/207388038-c913382e-066d-4172-95ab-db37fcc6fec1.png)

Looking forward to hearing back from you – thanks for your efforts!

**Comment by Chrystll** [comment]
I didn't reproduce your issue. Could you please contact me on our [helpdesk](https://polylang.pro/support/)? That will be easiest for me to investigate your issue. I would need that you provide me your json file to reproduce it as well the site health info of your site. It will allow me to know more about your installation and your Polylang settings.

I would need also that you specify if your field groups are translated in German and in English (the Field Groups checkbox is checked in the Custom post types and Taxonomies module).

**Comment by E-VANCE** [comment]
Hi @Chrystll,

thanks for getting back – I'll open a ticket via the helpdesk as requested.

**Comment by E-VANCE** [comment]
@Chrystll 
I have submitted a ticket more then a month ago now and have never heard back from anyone. This isn't what I would expect regarding supporting a paying customer 😑

Could you please look into this? Thanks.

**Comment by Chrystll** [comment]
@E-VANCE 
I just checked on my side and I didn't your support ticket related to your issue. Please contact me today via our support form just here https://polylang.pro/support/. Once done, please ping me on this GitHub issue so that I will check it right away.

**Comment by E-VANCE** [comment]
@Chrystll
My bad, seems like the ticket never was created in the first place although I could swear that I submitted the form correctly (the form fields were saved in my browser)...

You should have received the support request now.

Thanks & Regards

**Comment by Chrystll** [comment]
@E-VANCE 
I confirm that I have just received your support request. It will be handled today by our support team.

**Comment by kristjankoppel** [comment]
Commenting on this issue since i have the same problem and client lost some of they're translated and now even original pages. This is second website for me that have introduced this bug. 

@E-VANCE @Chrystll can you tell me if there was a solution to this problem?

**Comment by pixels-aromates** [comment]
> I am also seeing this on a website running WordPress 6.7, PHP 8.3, Polylang Pro 3.7.5 and ACF 6.6.2.
> 
> I have a post in the default language with a repeater field containing a text field.
> 
> I add a row, fill in the text field and save.
> 
> Then I create a translation, add two rows to this translated version and save. This translated post now has two text strings in its repeater and the default language has one text string.
> 
> Going back to the default language, the repeater field will now show two rows of text fields: the first text field is in the default language and the second text field contains the text string from second row of the translated post. Updating and saving the default language post causes these changes to appear on the translated post. For example, if I delete the second row in the default language, the translated language will also only have one row in its repeater field.

Same issue here

**Comment by madhavi-addweb** [comment]
> > I am also seeing this on a website running WordPress 6.7, PHP 8.3, Polylang Pro 3.7.5 and ACF 6.6.2.
> > I have a post in the default language with a repeater field containing a text field.
> > I add a row, fill in the text field and save.
> > Then I create a translation, add two rows to this translated version and save. This translated post now has two text strings in its repeater and the default language has one text string.
> > Going back to the default language, the repeater field will now show two rows of text fields: the first text field is in the default language and the second text field contains the text string from second row of the translated post. Updating and saving the default language post causes these changes to appear on the translated post. For example, if I delete the second row in the default language, the translated language will also only have one row in its repeater field.
> 
> Same issue here
