### ISSUE TITLE
Polylang not translating default title and meta description with using Yoast's Meta_Surface

### ISSUE THREAD

**Issue by gorkalaucirica** [polylang/polylang#913]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate. Related to #505 
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and enable Polylang 3.11 & Yoast 15.9.2
2. Translate post title
![Captura de pantalla 2021-09-08 a las 11 40 07](https://user-images.githubusercontent.com/1749891/132486055-9eabb513-91fa-414e-bde5-2f568884fe8b.png)
3. Use `YoastSEO()->meta->for_post(1)->title;` (Spanish post). 

## Expected behavior and actual behavior

When I follow those steps, I see English title.

I was expecting Spanish title.
